from kivy.app import App
from kivy.uix.screenmanager import ScreenManager
from KivyDesigns.final_round_animation.final_round_animation import FinalRoundAnimation
from KivyDesigns.one_round_three_dim.one_round_three_dim import OneRoundThreeDim
from KivyDesigns.main_menu.main_menu import MainMenu
from KivyDesigns.play.play import Play
from KivyDesigns.round_choice_five_dim.round_choice_five_dim import RoundChoiceFiveDim
from KivyDesigns.round_choice_four_dim.round_choice_four_dim import RoundChoiceFourDim
from KivyDesigns.round_choice_three_dim.round_choice_three_dim import RoundChoiceThreeDim
from KivyDesigns.screen_size.screen_size import ScreenSize
from KivyDesigns.settings.settings import SettingsScreen
from KivyDesigns.standard_flow.standard_flow import StandardFlow
from KivyDesigns.template.template import HiddenButton, NavigationButton, ButtonMenu
from KivyDesigns.ultimate_flow.ultimate_flow import UltimateFlow
from KivyDesigns.circle_wins.circle_wins import CircleWins
from KivyDesigns.cross_wins.cross_wins import CrossWins
from KivyDesigns.result.result import Result
from KivyDesigns.draw.draw import Draw
from KivyDesigns.two_rounds_three_dim.two_rounds_three_dim import TwoRoundsThreeDim
from KivyDesigns.round_one_animation.round_one_animation import RoundOneAnimation
from KivyDesigns.round_one_anim_three_rounds.round_one_anim_three_rounds import RoundOneAnimThreeRounds
from KivyDesigns.three_rounds_three_dim.three_rounds_three_dim import ThreeRoundsThreeDim
from KivyDesigns.two_rounds_three_dim.two_circle_wins_round_two import TwoCircleWinsRoundTwo
from KivyDesigns.two_rounds_three_dim.two_cross_wins_round_two import TwoCrossWinsRoundTwo
from KivyDesigns.two_rounds_three_dim.two_draw_final_round import TwoDrawFinalRound
from KivyDesigns.two_rounds_three_dim.two_circle_wins_final_round import TwoCircleWinsFinalRound
from KivyDesigns.two_rounds_three_dim.two_cross_wins_final_round import TwoCrossWinsFinalRound


class WindowManager(ScreenManager):
    pass
